/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package tree_diff;

public class App {

    private boolean serviceModeEnabled;
    private int servicePort;

    public static void main(String[] args) {
        /*
        * TODO: parse the arguments and set the port, server mode, etc.
        *  */
        App a = new App();
        a.serviceModeEnabled = true;
        a.servicePort = 8080;
        if(a.serviceModeEnabled) {
            TreeDiffWebService.runServer(a.servicePort);
        }
    }
}
