// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http_record.proto

package MahimahiProtobufs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestResponse_Scheme int32

const (
	RequestResponse_HTTP  RequestResponse_Scheme = 1
	RequestResponse_HTTPS RequestResponse_Scheme = 2
)

var RequestResponse_Scheme_name = map[int32]string{
	1: "HTTP",
	2: "HTTPS",
}

var RequestResponse_Scheme_value = map[string]int32{
	"HTTP":  1,
	"HTTPS": 2,
}

func (x RequestResponse_Scheme) Enum() *RequestResponse_Scheme {
	p := new(RequestResponse_Scheme)
	*p = x
	return p
}

func (x RequestResponse_Scheme) String() string {
	return proto.EnumName(RequestResponse_Scheme_name, int32(x))
}

func (x *RequestResponse_Scheme) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestResponse_Scheme_value, data, "RequestResponse_Scheme")
	if err != nil {
		return err
	}
	*x = RequestResponse_Scheme(value)
	return nil
}

func (RequestResponse_Scheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e3f6dc3e8414886, []int{2, 0}
}

type HTTPMessage struct {
	FirstLine            []byte        `protobuf:"bytes,1,opt,name=first_line,json=firstLine" json:"first_line,omitempty"`
	Header               []*HTTPHeader `protobuf:"bytes,2,rep,name=header" json:"header,omitempty"`
	Body                 []byte        `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HTTPMessage) Reset()         { *m = HTTPMessage{} }
func (m *HTTPMessage) String() string { return proto.CompactTextString(m) }
func (*HTTPMessage) ProtoMessage()    {}
func (*HTTPMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e3f6dc3e8414886, []int{0}
}

func (m *HTTPMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPMessage.Unmarshal(m, b)
}
func (m *HTTPMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPMessage.Marshal(b, m, deterministic)
}
func (m *HTTPMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPMessage.Merge(m, src)
}
func (m *HTTPMessage) XXX_Size() int {
	return xxx_messageInfo_HTTPMessage.Size(m)
}
func (m *HTTPMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPMessage proto.InternalMessageInfo

func (m *HTTPMessage) GetFirstLine() []byte {
	if m != nil {
		return m.FirstLine
	}
	return nil
}

func (m *HTTPMessage) GetHeader() []*HTTPHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HTTPMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HTTPHeader struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPHeader) Reset()         { *m = HTTPHeader{} }
func (m *HTTPHeader) String() string { return proto.CompactTextString(m) }
func (*HTTPHeader) ProtoMessage()    {}
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e3f6dc3e8414886, []int{1}
}

func (m *HTTPHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPHeader.Unmarshal(m, b)
}
func (m *HTTPHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPHeader.Marshal(b, m, deterministic)
}
func (m *HTTPHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPHeader.Merge(m, src)
}
func (m *HTTPHeader) XXX_Size() int {
	return xxx_messageInfo_HTTPHeader.Size(m)
}
func (m *HTTPHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPHeader.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPHeader proto.InternalMessageInfo

func (m *HTTPHeader) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *HTTPHeader) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RequestResponse struct {
	Ip                   *string                 `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port                 *uint32                 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Scheme               *RequestResponse_Scheme `protobuf:"varint,3,opt,name=scheme,enum=MahimahiProtobufs.RequestResponse_Scheme" json:"scheme,omitempty"`
	Request              *HTTPMessage            `protobuf:"bytes,4,opt,name=request" json:"request,omitempty"`
	Response             *HTTPMessage            `protobuf:"bytes,5,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e3f6dc3e8414886, []int{2}
}

func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (m *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(m, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *RequestResponse) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *RequestResponse) GetScheme() RequestResponse_Scheme {
	if m != nil && m.Scheme != nil {
		return *m.Scheme
	}
	return RequestResponse_HTTP
}

func (m *RequestResponse) GetRequest() *HTTPMessage {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RequestResponse) GetResponse() *HTTPMessage {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterEnum("MahimahiProtobufs.RequestResponse_Scheme", RequestResponse_Scheme_name, RequestResponse_Scheme_value)
	proto.RegisterType((*HTTPMessage)(nil), "MahimahiProtobufs.HTTPMessage")
	proto.RegisterType((*HTTPHeader)(nil), "MahimahiProtobufs.HTTPHeader")
	proto.RegisterType((*RequestResponse)(nil), "MahimahiProtobufs.RequestResponse")
}

func init() { proto.RegisterFile("http_record.proto", fileDescriptor_6e3f6dc3e8414886) }

var fileDescriptor_6e3f6dc3e8414886 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4f, 0x02, 0x31,
	0x10, 0xc5, 0xb3, 0xe5, 0x8f, 0x30, 0x28, 0xc2, 0xc4, 0x43, 0x2f, 0x18, 0xb2, 0x27, 0xbc, 0xec,
	0x81, 0x68, 0x62, 0xbc, 0x79, 0xe3, 0x20, 0x09, 0x29, 0xdc, 0xc9, 0xc2, 0x0e, 0x6e, 0x23, 0x6c,
	0x6b, 0xdb, 0xd5, 0xf0, 0x21, 0xfc, 0xce, 0xa6, 0xdd, 0x55, 0x13, 0xff, 0x24, 0xde, 0xde, 0x4c,
	0x7e, 0xef, 0xcd, 0x6b, 0x61, 0x98, 0x3b, 0xa7, 0xd7, 0x86, 0xb6, 0xca, 0x64, 0x89, 0x36, 0xca,
	0x29, 0x1c, 0xce, 0xd3, 0x5c, 0x1e, 0xd2, 0x5c, 0x2e, 0xfc, 0xb8, 0x29, 0x77, 0x36, 0x7e, 0x85,
	0xde, 0x6c, 0xb5, 0x5a, 0xcc, 0xc9, 0xda, 0xf4, 0x91, 0x70, 0x04, 0xb0, 0x93, 0xc6, 0xba, 0xf5,
	0x5e, 0x16, 0xc4, 0xa3, 0x71, 0x34, 0x39, 0x15, 0xdd, 0xb0, 0x79, 0x90, 0x05, 0xe1, 0x0d, 0xb4,
	0x73, 0x4a, 0x33, 0x32, 0x9c, 0x8d, 0x1b, 0x93, 0xde, 0x74, 0x94, 0xfc, 0x48, 0x4c, 0x7c, 0xdc,
	0x2c, 0x40, 0xa2, 0x86, 0x11, 0xa1, 0xb9, 0x51, 0xd9, 0x91, 0x37, 0x42, 0x5e, 0xd0, 0xf1, 0x35,
	0xc0, 0x17, 0x89, 0x03, 0x68, 0x3c, 0xd1, 0xb1, 0x3e, 0xe8, 0x25, 0x5e, 0x40, 0xeb, 0x25, 0xdd,
	0x97, 0xc4, 0x59, 0xd8, 0x55, 0x43, 0xfc, 0xc6, 0xe0, 0x5c, 0xd0, 0x73, 0x49, 0xd6, 0x09, 0xb2,
	0x5a, 0x15, 0x96, 0xb0, 0x0f, 0x4c, 0xea, 0x60, 0xed, 0x0a, 0x26, 0xb5, 0xbf, 0xa6, 0x95, 0x71,
	0xc1, 0x78, 0x26, 0x82, 0xc6, 0x7b, 0x68, 0xdb, 0x6d, 0x4e, 0x07, 0x0a, 0x1d, 0xfa, 0xd3, 0xab,
	0x5f, 0x8a, 0x7f, 0xcb, 0x4d, 0x96, 0xc1, 0x20, 0x6a, 0x23, 0xde, 0xc2, 0x89, 0xa9, 0x08, 0xde,
	0x1c, 0x47, 0x93, 0xde, 0xf4, 0xf2, 0x8f, 0xc7, 0xd7, 0x7f, 0x29, 0x3e, 0x70, 0xbc, 0x83, 0x8e,
	0xa9, 0x43, 0x79, 0xeb, 0x5f, 0xd6, 0x4f, 0x3e, 0x1e, 0x41, 0xbb, 0xea, 0x81, 0x1d, 0x68, 0x7a,
	0x64, 0x10, 0x61, 0x17, 0x5a, 0x5e, 0x2d, 0x07, 0xec, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xb8,
	0xa7, 0xa8, 0xe5, 0x01, 0x00, 0x00,
}
