# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import policy_service_pb2 as policy__service__pb2


class PolicyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPolicy = channel.unary_unary(
        '/PolicyService/GetPolicy',
        request_serializer=policy__service__pb2.Page.SerializeToString,
        response_deserializer=policy__service__pb2.Policy.FromString,
        )


class PolicyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPolicy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.GetPolicy,
          request_deserializer=policy__service__pb2.Page.FromString,
          response_serializer=policy__service__pb2.Policy.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PolicyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
