/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree_diff;

import eu.mihosoft.ext.apted.distance.APTED;
import eu.mihosoft.ext.apted.node.Node;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    /**
     * Tests if equal strings have zero edit distance
     * string is JSON representation of a tree
     */
    @Test public void equalTreesHaveZeroEditDistance() {
        App classUnderTest = new App();
        InputParser parser = new InputParser();
        Node<NodeData> t1 = parser.fromString("{\"0\":{\"children\":[1,2],\"size\":100,\"type\":\"text/html\"},\"1\":{\"children\":[],\"size\":75,\"type\":\"image/jpeg\"},\"2\":{\"children\":[],\"size\":50,\"type\":\"text/css\"},\"length\":3}");
        Node<NodeData> t2 = parser.fromString("{\"0\":{\"children\":[1,2],\"size\":100,\"type\":\"text/html\"},\"1\":{\"children\":[],\"size\":75,\"type\":\"image/jpeg\"},\"2\":{\"children\":[],\"size\":50,\"type\":\"text/css\"},\"length\":3}");
        APTED<CostModel, NodeData> apted = new APTED<>(new CostModel());
        float result = apted.computeEditDistance(t1, t2);
        assertEquals(result, 0.0, 0);
    }
}
